### ISSUE TITLE
No such file or directory: '/home/notebook/code/personal/S9052995/syn_pro/OpenOOD/data/txtfiles'

### ISSUE THREAD

**Issue by BRONYA-818** [YBZh/OpenOOD-VLM#2]
Hi, I'm impressed by your wonderful work!
However, I met following bugs which stopped me from reproducing your results.
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    launch(
  File "./OpenOOD-VLM/openood/utils/launch.py", line 84, in launch
    main_func(*args)
  File "main.py", line 24, in main
    pipeline.run()
  File "./OpenOOD-VLM/openood/pipelines/test_ood_pipeline.py", line 23, in run
    net = get_network(self.config.network)
  File "./OpenOOD-VLM/openood/networks/utils.py", line 108, in get_network
    net = CoOp_NegOODPrompt(network_config)
  File "./OpenOOD-VLM/openood/networks/clip_coop_negprompt.py", line 892, in __init__
    self.model = CustomCLIP(cfg, classnames, clip_model)
  File "./OpenOOD-VLM/openood/networks/clip_coop_negprompt.py", line 719, in __init__
    self.prompt_learner = PromptLearner(cfg.backbone, classnames, clip_model)
  File "./OpenOOD-VLM/openood/networks/clip_coop_negprompt.py", line 599, in __init__
    selected_adj_text, selected_noun_text, unselected_adj_text, unselected_noun_text = get_selected_ood_text_list(self.OOD_NUM)
  File "./OpenOOD-VLM/openood/networks/clip_coop_negprompt.py", line 410, in get_selected_ood_text_list
    generate_cossim_idname_wordnet_dedup(classnames, wordnet_processed_path)
  File "./OpenOOD-VLM/openood/networks/clip_for_wordnet_prepare.py", line 93, in generate_cossim_idname_wordnet_dedup
    text_files = os.listdir(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/notebook/code/personal/S9052995/syn_pro/OpenOOD/data/txtfiles'
It seems that there is a missing file named "txtfiles", I wonder if you can provide the file, thanks!

**Comment by YBZh** [comment]
Thanks for your attention. You can download txtfiles from: [txtfiles](https://github.com/XueJiang16/NegLabel/tree/main/txtfiles)
